/**
 * @copyright 2026 Agenticwork LLC
 * @license PROPRIETARY
 */

import { ExportData, ChatMessage } from './types';

/**
 * Formats export data as Markdown
 */
export function formatMarkdown(data: ExportData): string {
  const { session, exportOptions, userInfo } = data;
  
  let markdown = '';
  
  // Header
  markdown += `# ${session.title}\n\n`;
  
  // Metadata
  if (exportOptions.includeMetadata) {
    markdown += `## Session Information\n\n`;
    markdown += `- **Created:** ${new Date(session.createdAt).toLocaleString()}\n`;
    markdown += `- **Last Updated:** ${new Date(session.updatedAt).toLocaleString()}\n`;
    markdown += `- **Message Count:** ${session.messages.length}\n`;
    
    if (session.metadata) {
      if (session.metadata.model) markdown += `- **Model:** ${session.metadata.model}\n`;
      if (session.metadata.totalTokens) markdown += `- **Total Tokens:** ${session.metadata.totalTokens.toLocaleString()}\n`;
      if (session.metadata.totalCost) markdown += `- **Estimated Cost:** $${session.metadata.totalCost.toFixed(4)}\n`;
    }
    
    if (userInfo?.name) markdown += `- **User:** ${userInfo.name}\n`;
    markdown += `- **Exported:** ${new Date(data.exportedAt).toLocaleString()}\n\n`;
  }
  
  // Messages
  markdown += `## Conversation\n\n`;
  
  session.messages.forEach((message, index) => {
    const roleEmoji = message.role === 'user' ? '👤' : message.role === 'assistant' ? '🤖' : '⚙️';
    
    markdown += `### ${roleEmoji} ${message.role.charAt(0).toUpperCase() + message.role.slice(1)}`;
    
    if (exportOptions.includeTimestamps) {
      markdown += ` *(${new Date(message.timestamp).toLocaleString()})*`;
    }
    
    if (exportOptions.includeTokenUsage && message.tokenUsage) {
      markdown += ` • ${message.tokenUsage.totalTokens} tokens`;
    }
    
    markdown += `\n\n${message.content}\n\n`;
    
    if (index < session.messages.length - 1) {
      markdown += `---\n\n`;
    }
  });
  
  // Footer
  markdown += `\n---\n\n*Generated by AgenticWork Chat • Professional AI Assistant*\n`;
  
  return markdown;
}

/**
 * Formats export data as HTML
 */
export function generateHTML(data: ExportData): string {
  const { session, exportOptions, userInfo } = data;
  const isDark = exportOptions.theme === 'dark';
  
  const colors = isDark ? {
    bg: '#111827',
    cardBg: '#1f2937',
    text: '#f3f4f6',
    textSecondary: '#9ca3af',
    border: '#374151',
    accent: '#3b82f6'
  } : {
    bg: '#ffffff',
    cardBg: '#f8fafc',
    text: '#111827',
    textSecondary: '#6b7280',
    border: '#e5e7eb',
    accent: '#3b82f6'
  };
  
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${session.title} - Chat Export</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
      font-size: 14px;
      line-height: 1.6;
      color: ${colors.text};
      background: ${colors.bg};
      padding: 40px 20px;
      max-width: 800px;
      margin: 0 auto;
    }
    
    .header {
      text-align: center;
      padding: 30px 0 40px;
      border-bottom: 2px solid ${colors.accent};
      margin-bottom: 40px;
    }
    
    .header h1 {
      font-size: 32px;
      font-weight: 700;
      color: ${colors.text};
      margin-bottom: 10px;
    }
    
    .header .subtitle {
      font-size: 16px;
      color: ${colors.textSecondary};
    }
    
    .metadata {
      background: ${colors.cardBg};
      border: 1px solid ${colors.border};
      border-radius: 12px;
      padding: 25px;
      margin-bottom: 40px;
    }
    
    .metadata h2 {
      font-size: 18px;
      font-weight: 600;
      color: ${colors.text};
      margin-bottom: 15px;
    }
    
    .metadata-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 10px;
    }
    
    .metadata-item {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid ${colors.border};
      font-size: 13px;
    }
    
    .metadata-label {
      font-weight: 600;
      color: ${colors.textSecondary};
    }
    
    .metadata-value {
      color: ${colors.text};
    }
    
    .messages {
      margin-bottom: 40px;
    }
    
    .messages h2 {
      font-size: 20px;
      font-weight: 600;
      color: ${colors.text};
      margin-bottom: 30px;
      padding-bottom: 10px;
      border-bottom: 1px solid ${colors.border};
    }
    
    .message {
      margin-bottom: 30px;
      border: 1px solid ${colors.border};
      border-radius: 12px;
      overflow: hidden;
      background: ${colors.cardBg};
    }
    
    .message-header {
      background: ${isDark ? '#374151' : '#ffffff'};
      padding: 15px 20px;
      border-bottom: 1px solid ${colors.border};
      display: flex;
      align-items: center;
      gap: 12px;
    }
    
    .message-avatar {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 16px;
      font-weight: 600;
      color: white;
    }
    
    .message-avatar.user {
      background: #3b82f6;
    }
    
    .message-avatar.assistant {
      background: #8b5cf6;
    }
    
    .message-avatar.system {
      background: #6b7280;
    }
    
    .message-info {
      flex: 1;
    }
    
    .message-role {
      font-weight: 600;
      font-size: 14px;
      text-transform: capitalize;
      color: ${colors.text};
    }
    
    .message-timestamp {
      font-size: 12px;
      color: ${colors.textSecondary};
    }
    
    .token-usage {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      background: ${colors.accent}20;
      color: ${colors.accent};
      padding: 4px 10px;
      border-radius: 12px;
      font-size: 11px;
      font-weight: 500;
    }
    
    .message-content {
      padding: 20px;
      font-size: 14px;
      line-height: 1.6;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    
    .message-content pre {
      background: ${isDark ? '#000000' : '#f3f4f6'};
      border: 1px solid ${colors.border};
      border-radius: 6px;
      padding: 15px;
      overflow-x: auto;
      font-family: 'JetBrains Mono', 'Fira Code', monospace;
      font-size: 12px;
      margin: 15px 0;
    }
    
    .message-content code {
      background: ${isDark ? '#374151' : '#e5e7eb'};
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'JetBrains Mono', 'Fira Code', monospace;
      font-size: 12px;
    }
    
    .footer {
      text-align: center;
      padding-top: 30px;
      border-top: 1px solid ${colors.border};
      color: ${colors.textSecondary};
      font-size: 12px;
    }
    
    .footer .logo {
      font-size: 20px;
      margin-bottom: 10px;
    }
    
    ${exportOptions.customStyles || ''}
  </style>
</head>
<body>
  <div class="header">
    <h1>${session.title}</h1>
    <p class="subtitle">AgenticWork Chat Export</p>
  </div>
  
  ${exportOptions.includeMetadata ? `
  <div class="metadata">
    <h2>Session Information</h2>
    <div class="metadata-grid">
      <div class="metadata-item">
        <span class="metadata-label">Created:</span>
        <span class="metadata-value">${new Date(session.createdAt).toLocaleString()}</span>
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Last Updated:</span>
        <span class="metadata-value">${new Date(session.updatedAt).toLocaleString()}</span>
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Messages:</span>
        <span class="metadata-value">${session.messages.length}</span>
      </div>
      ${session.metadata?.model ? `
      <div class="metadata-item">
        <span class="metadata-label">Model:</span>
        <span class="metadata-value">${session.metadata.model}</span>
      </div>
      ` : ''}
      ${session.metadata?.totalTokens ? `
      <div class="metadata-item">
        <span class="metadata-label">Total Tokens:</span>
        <span class="metadata-value">${session.metadata.totalTokens.toLocaleString()}</span>
      </div>
      ` : ''}
      ${userInfo?.name ? `
      <div class="metadata-item">
        <span class="metadata-label">User:</span>
        <span class="metadata-value">${userInfo.name}</span>
      </div>
      ` : ''}
      <div class="metadata-item">
        <span class="metadata-label">Exported:</span>
        <span class="metadata-value">${new Date(data.exportedAt).toLocaleString()}</span>
      </div>
    </div>
  </div>
  ` : ''}
  
  <div class="messages">
    <h2>Conversation</h2>
    ${session.messages.map(message => {
      const roleEmoji = message.role === 'user' ? '👤' : message.role === 'assistant' ? '🤖' : '⚙️';
      
      return `
        <div class="message">
          <div class="message-header">
            <div class="message-avatar ${message.role}">${roleEmoji}</div>
            <div class="message-info">
              <div class="message-role">${message.role}</div>
              ${exportOptions.includeTimestamps ? `
              <div class="message-timestamp">${new Date(message.timestamp).toLocaleString()}</div>
              ` : ''}
            </div>
            ${exportOptions.includeTokenUsage && message.tokenUsage ? `
            <span class="token-usage">🔢 ${message.tokenUsage.totalTokens} tokens</span>
            ` : ''}
          </div>
          <div class="message-content">${formatContentForHTML(message.content)}</div>
        </div>
      `;
    }).join('')}
  </div>
  
  <div class="footer">
    <div class="logo">🤖</div>
    <p>Generated by AgenticWork Chat • Professional AI Assistant</p>
    <p>Exported on ${new Date(data.exportedAt).toLocaleString()}</p>
  </div>
</body>
</html>`;
}

/**
 * Formats export data as JSON
 */
export function formatJSON(data: ExportData): string {
  const exportData = {
    format: 'agenticwork-chat-export',
    version: '1.0',
    exportedAt: data.exportedAt,
    session: {
      id: data.session.id,
      title: data.session.title,
      createdAt: data.session.createdAt,
      updatedAt: data.session.updatedAt,
      metadata: data.session.metadata,
      messages: data.session.messages.map(message => ({
        id: message.id,
        role: message.role,
        content: message.content,
        timestamp: message.timestamp,
        tokenUsage: message.tokenUsage,
        toolCalls: message.toolCalls,
        mcpCalls: message.mcpCalls
      }))
    },
    exportOptions: data.exportOptions,
    userInfo: data.userInfo,
    statistics: {
      totalMessages: data.session.messages.length,
      userMessages: data.session.messages.filter(m => m.role === 'user').length,
      assistantMessages: data.session.messages.filter(m => m.role === 'assistant').length,
      systemMessages: data.session.messages.filter(m => m.role === 'system').length,
      totalTokens: data.session.messages.reduce((sum, m) => sum + (m.tokenUsage?.totalTokens || 0), 0),
      averageTokensPerMessage: Math.round(
        data.session.messages.reduce((sum, m) => sum + (m.tokenUsage?.totalTokens || 0), 0) / 
        data.session.messages.length || 0
      ),
      conversationDuration: Math.round(
        (new Date(data.session.updatedAt).getTime() - new Date(data.session.createdAt).getTime()) / 60000
      ) // minutes
    }
  };
  
  return JSON.stringify(exportData, null, 2);
}

/**
 * Helper function to format message content for HTML export
 */
function formatContentForHTML(content: string): string {
  return content
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
    .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/\n/g, '<br>');
}